run:
  allow-parallel-runners: true
  go: "1.17"

issues:
  exclude-use-default: false
  max-same-issues: 0
  new-from-rev: HEAD
  exclude-rules:
    - linters:
        - cyclop
      path: cmd
  exclude-files:
    - 'generator/*\\.go$'

linters:
  disable-all: true
  enable:
    - gosimple
    - govet
    - gofmt
    - goimports
    - staticcheck
    - tenv
    - gocyclo
    - cyclop
    - errcheck
    - unused
    - ineffassign
    - asciicheck
    - bodyclose
    - containedctx
    - contextcheck
    - makezero
    - nilerr

linters-settings:
  gofmt:
    simplify: true

  exhaustive:
    default-signifies-exhaustive: true

  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: true
    require-specific: true

  errorlint:
    errorf: false

  gocyclo:
    min-complexity: 15

  cyclop:
    max-complexity: 15
    package-average: 0.5
    skip-tests: true
