name: "Check For API Spec Updates"

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  compare_to_new_spec:
    runs-on: ubuntu-latest
    name: Compare to new API spec
    outputs:
      isNew: ${{ steps.diff.outputs.isNew }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Pull new spec
        run: |
          curl -SLo openAPIDefinition_new.json "$SPEC_URL"
        env:
          SPEC_URL: https://dfv3qgd2ykmrx.cloudfront.net/api_spec/release/v2.json
      - name: Diff
        id: diff
        run: |
          if [ $(diff openAPIDefinition_new.json openAPIDefinition.json | wc -l) -gt 0 ]; then
            echo "isNew=true" >> $GITHUB_OUTPUT
          else
            echo "isNew=false" >> $GITHUB_OUTPUT
          fi
  notify:
    runs-on: ubuntu-latest
    name: Notify on telegram
    needs:
      - compare_to_new_spec
    if: needs.compare_to_new_spec.outputs.isNew == 'true'
    steps:
      - name: Notification via telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            New NEON API spec detected. Please take action.
